# Generated by Django 4.2.1 on 2023-06-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excursion',
            options={'verbose_name': 'excursion', 'verbose_name_plural': 'excursiones'},
        ),
        migrations.AlterModelOptions(
            name='formapago',
            options={'verbose_name': 'forma de pago'},
        ),
        migrations.AddField(
            model_name='formapago',
            name='descripcion',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
